
name: Close Old Issues

on: 
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-close: 7
          stale-issue-message: 'This issue is stale because it has been open for 7 days with no activity. It will be closed in 7 days if no further activity occurs.'
          close-issue-message: 'This issue was closed because it has been inactive for 14 days.'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 30
